# -*- coding: utf-8 -*-
"""vector_store.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x3YJkJOBuF55pzTq50UqWUcdzYYslJM5
"""

pip install -U langchain langchain-community chromadb sentence-transformers

from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import Chroma
from langchain_core.documents import Document

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

#create langchain documents for IPL Players

documents = [
    Document(
        page_content=(
            "Virat Kohli is a right-handed batsman who plays for Royal Challengers Bangalore "
            "in the Indian Premier League. He is known for his consistency, aggressive batting "
            "style, and leadership qualities."
        ),
        metadata={
            "player_name": "Virat Kohli",
            "team": "Royal Challengers Bangalore",
            "role": "Batsman",
            "country": "India"
        }
    ),

    Document(
        page_content=(
            "MS Dhoni is a legendary wicket-keeper batsman and former captain of Chennai Super Kings. "
            "He is famous for his calm demeanor, finishing abilities, and tactical brilliance."
        ),
        metadata={
            "player_name": "MS Dhoni",
            "team": "Chennai Super Kings",
            "role": "Wicket-Keeper Batsman",
            "country": "India"
        }
    ),

    Document(
        page_content=(
            "Rohit Sharma is an opening batsman representing Mumbai Indians in the IPL. "
            "He is known for his elegant stroke play and record number of IPL titles as a captain."
        ),
        metadata={
            "player_name": "Rohit Sharma",
            "team": "Mumbai Indians",
            "role": "Batsman",
            "country": "India"
        }
    ),

    Document(
        page_content=(
            "Jasprit Bumrah is a fast bowler for Mumbai Indians. "
            "He is renowned for his unorthodox bowling action, deadly yorkers, "
            "and effectiveness in death overs."
        ),
        metadata={
            "player_name": "Jasprit Bumrah",
            "team": "Mumbai Indians",
            "role": "Bowler",
            "country": "India"
        }
    )
]

vector_store = Chroma(
    embedding_function = embeddings,
    persist_directory = 'chroma-db',
    collection_name = 'sample'
)

vector_store.add_documents(documents) # to add documents in the vector store

vector_store.get(include=['embeddings', 'documents', 'metadatas']) #view documents

# search doocuments
vector_store.similarity_search(
    query='who among there are a bowler',
    k=2
)

#search with similarity score
vector_store.similarity_search_with_score(
    query='who among there are a bowler',
    k=2
)

